[project]
name = "x-feed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "feedparser>=6.0.11",
    "requests>=2.32.3",
    "requests-oauthlib>=2.0.0",
]
