name: RSS Tweet Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run script in container
        uses: docker://ghcr.io/anthonyrussano/x-feed/main:latest
        env:
          OAUTH_CONSUMER_KEY: ${{ secrets.OAUTH_CONSUMER_KEY }}
          OAUTH_CONSUMER_SECRET: ${{ secrets.OAUTH_CONSUMER_SECRET }}
          OAUTH_ACCESS_TOKEN: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          OAUTH_ACCESS_TOKEN_SECRET: ${{ secrets.OAUTH_ACCESS_TOKEN_SECRET }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'logs/*'
          message: 'Update logs'
          default_author: github_actions
          push: true